import ja from './translations/copy-ja.mjs';
import de from './translations/copy-de.mjs';
import fr from './translations/copy-fr.mjs';
import ko from './translations/copy-ko.mjs';

export const copy = {
  zh: {
    lang: 'zh-CN', title: 'X-Science — 科学软件与研究 Agent',
    description: '探索 Victor Xu 开发的开源科学软件与研究 Agent：X-Science、X-Pharma、X-DDE、X-Synth 与 X-PatentSAR。',
    nav: ['软件与 Agent', '研究工作流', '关于'], explore: '探索产品', github: '在 GitHub 查看',
    heroLabel: '独立开发 · 科学驱动', heroLines: ['让科学，', '继续向前。'],
    heroText: '为真实研究打造的软件与 Agent。连接证据、分子、工具与人，让每一个研究问题都能走向下一步。',
    heroFoot: '面向生物医药研究者、药物化学家与研发团队', concept: '品牌概念视觉',
    strip: ['开放源码', '研究者导向', '自主部署', '可追溯的证据'],
    productLabel: '软件与 Agent', productTitle: '各有所长。一起向前。',
    productText: '从医药情报到分子设计，从研究 Agent 到合成路线。找到适合你当前问题的工具。',
    categories: { all: '全部产品', agents: '研究 Agent', intelligence: '医药情报', discovery: '药物发现', chemistry: '化学研究' },
    details: '了解产品', count: '个产品', openSource: '开放源码',
    featureLabel: '走进研究工作台', featureTitle: '看见结构。看清研究。',
    featureText: 'X-DDE 将研究输入、科学计算和候选结果放在同一工作空间。表格里的分子，能在三维视图中逐一检查。',
    actualCaption: '实际界面 · X-DDE v0.4.49 · BRD4–JQ1 公开研究案例',
    workflowLabel: '研究路径', workflowTitle: '让下一个问题，\n有一个起点。',
    workflowText: '这些产品覆盖研究的不同环节。你可以独立使用，也可以复核各自的输出，再作为下一阶段的材料。',
    workflowNote: '下图是研究路径建议。产品间的数据交接需要按格式与方法复核。',
    workflowSteps: ['了解证据', '看清结构', '设计候选', '研究合成'],
    aboutLabel: '研究者开发', aboutTitle: '从研发问题出发，\n把工具做进研究。',
    aboutText: '我是 Victor Xu，药物发现研究者与独立 AI 工具开发者。我的工作横跨药物化学、AIDD / CADD、PROTAC 与分子胶，也在持续构建让研究更连贯的软件。',
    aboutText2: 'X-Science 是这些产品的共同入口。每个产品保留独立的定位、源码、许可与使用文档。',
    profile: '认识开发者', collaborate: '交流与合作',
    contactTitle: '你的下一个研究问题，\n从这里开始。', contactText: '探索源码，阅读文档，或与我交流你的研究需求。',
    footerText: '科学软件与研究 Agent，由 Victor Xu 开发。',
    licenseNote: '各产品遵循各自的源码、模型与数据许可。', footerNav: ['全部产品', 'GitHub', 'LinkedIn'],
    skip: '跳到正文', menu: '打开导航', closeMenu: '关闭导航',
    back: '全部产品', capabilities: '为你的研究提供什么', workflow: '如何开始',
    audience: '适合谁', environment: '运行环境', license: '第一方源码许可',
    install: '安装与使用', source: '查看源码', releases: '获取发行版', guide: '深入了解',
    boundaryTitle: '选用前了解', imageSource: '图片来源与说明',
    next: '继续探索', nextTitle: '找到下一件研究工具。',
    facts: '介绍依据公开仓库资料，核对日期：2026-10-08。',
    notFound: '这个页面还没找到。', goHome: '返回首页',
  },
  en: {
    lang: 'en', title: 'X-Science — Scientific software & research agents',
    description: 'Explore open-source scientific software and research agents built by Victor Xu: X-Science, X-Pharma, X-DDE, X-Synth, and X-PatentSAR.',
    nav: ['Software & agents', 'Research workflows', 'About'], explore: 'Explore the software', github: 'Explore on GitHub',
    heroLabel: 'INDEPENDENTLY BUILT. SCIENCE DRIVEN.', heroLines: ['Move science', 'forward.'],
    heroText: 'Software and agents for real research. Connecting evidence, molecules, tools and people, so every question can lead somewhere new.',
    heroFoot: 'For biomedical researchers, medicinal chemists and R&D teams', concept: 'Brand concept visual',
    strip: ['Open source', 'Researcher focused', 'Self-hosted', 'Traceable evidence'],
    productLabel: 'THE SOFTWARE COLLECTION', productTitle: 'Distinct tools. Shared curiosity.',
    productText: 'From pharmaceutical intelligence to molecular design. From research agents to synthesis. Find a tool for the question in front of you.',
    categories: { all: 'All software', agents: 'Research agents', intelligence: 'Intelligence', discovery: 'Drug discovery', chemistry: 'Chemistry' },
    details: 'Explore product', count: 'products', openSource: 'Open source',
    featureLabel: 'INSIDE THE WORKBENCH', featureTitle: 'See the structure. See the work.',
    featureText: 'X-DDE brings research inputs, scientific calculations and candidates into one workspace. Inspect the molecules in the table, one by one, in three dimensions.',
    actualCaption: 'Actual interface · X-DDE v0.4.49 · Public BRD4–JQ1 research example',
    workflowLabel: 'A RESEARCH JOURNEY', workflowTitle: 'Give the next question\na place to start.',
    workflowText: 'Each product supports a different part of research. Use them independently, or review their outputs as material for the next stage.',
    workflowNote: 'An illustrative research path. Cross-product handoffs require review of formats and methods.',
    workflowSteps: ['Explore evidence', 'Inspect structures', 'Design candidates', 'Research synthesis'],
    aboutLabel: 'BUILT BY A RESEARCHER', aboutTitle: 'Built from the questions\nthat research brings.',
    aboutText: 'I’m Victor Xu, a drug discovery scientist and independent AI tool builder. My work spans medicinal chemistry, AIDD / CADD, PROTACs and molecular glues, alongside software that helps research move forward.',
    aboutText2: 'X-Science is the shared entry point to these products. Each has its own focus, source, license and documentation.',
    profile: 'Meet the developer', collaborate: 'Connect & collaborate',
    contactTitle: 'Your next research question\nstarts here.', contactText: 'Explore the source. Read the documentation. Or connect about your research needs.',
    footerText: 'Scientific software and research agents, built by Victor Xu.',
    licenseNote: 'Each product retains its own source, model and data licenses.', footerNav: ['All software', 'GitHub', 'LinkedIn'],
    skip: 'Skip to content', menu: 'Open navigation', closeMenu: 'Close navigation',
    back: 'All software', capabilities: 'Made for the work you do', workflow: 'A place to begin',
    audience: 'Who it is for', environment: 'Environment', license: 'First-party source license',
    install: 'Installation & usage', source: 'View the source', releases: 'Get the release', guide: 'Explore the documentation',
    boundaryTitle: 'Before you choose', imageSource: 'Image source & context',
    next: 'KEEP EXPLORING', nextTitle: 'Find your next research tool.',
    facts: 'Based on public repository material, reviewed on 2026-10-08.',
    notFound: 'This page hasn’t been found.', goHome: 'Back to the home page',
  },
  ja, de, fr, ko,
};

const labels = {
  zh: ['选择语言', '主导航', '按研究方向筛选软件', '查看完整截图', '产品概念图形', 'AI 生成概念图', 'X-Science 科学软件与研究 Agent'],
  en: ['Choose language', 'Main navigation', 'Filter software by research area', 'View the full screenshot', 'Product concept graphic', 'AI-generated concept art', 'X-Science scientific software & research agents'],
  ja: ['言語を選択', '主なナビゲーション', '研究分野で製品を絞り込む', '画像全体を見る', '製品コンセプト図', 'AI 生成のコンセプト図', 'X-Science の科学ソフトウェアと研究エージェント'],
  de: ['Sprache auswählen', 'Hauptnavigation', 'Produkte nach Forschungsgebiet filtern', 'Vollständiges Bild ansehen', 'Produktkonzeptgrafik', 'KI-generierte Konzeptgrafik', 'Wissenschaftliche Software & Forschungsagenten von X-Science'],
  fr: ['Choisir la langue', 'Navigation principale', 'Filtrer par domaine de recherche', 'Voir l’image complète', 'Visuel conceptuel du produit', 'Visuel conceptuel généré par IA', 'Logiciels scientifiques & agents de recherche X-Science'],
  ko: ['언어 선택', '주요 메뉴', '연구 분야로 제품 필터링', '전체 이미지 보기', '제품 콘셉트 그래픽', 'AI 생성 콘셉트 이미지', 'X-Science 과학 소프트웨어와 연구 에이전트'],
};
for (const [lang, values] of Object.entries(labels)) {
  [copy[lang].languageLabel, copy[lang].navigationLabel, copy[lang].filterLabel, copy[lang].fullImage, copy[lang].conceptGraphic, copy[lang].generatedLabel, copy[lang].heroAlt] = values;
}
