export const interactionCopy = {
  en: {
    search: 'Find a research tool', searchPlaceholder: 'Search tools, methods or research areas…',
    searchHint: 'Search the collection or choose a research area.', emptyTitle: 'A different question?',
    emptyText: 'No tools match these filters. Try another term or explore the full collection.', reset: 'Show all tools',
    heroBottom: '01 — EXPLORE WHAT’S NEXT', creatorRole: 'Drug discovery scientist & AI tool builder', contactLabel: 'LET’S EXPLORE',
    capabilitiesLabel: 'CAPABILITIES', firstWorkflowLabel: 'YOUR FIRST WORKFLOW',
    chooseStage: 'Choose your starting point', stageTools: 'Tools for this stage',
    stageDescriptions: [
      'Start with literature, pharmaceutical intelligence or patent evidence. Keep the original sources close to the question.',
      'Inspect structures and organize a research task. Review molecular context before choosing a computational method.',
      'Explore candidate generation and molecular design. Review the inputs, model requirements and outputs of each tool.',
      'Explore synthesis routes and starting materials. Assess route suggestions using chemical judgment and source evidence.',
    ],
    closeImage: 'Close image', loadingImage: 'Loading the full image…', imageError: 'The image could not load. Open the original file to try again.',
    openOriginal: 'Open original image', imageTitle: 'A closer look', sectionNavigation: 'On this page',
    sectionLabels: ['Capabilities', 'Getting started', 'Before you choose'],
  },
  zh: {
    search: '查找研究工具', searchPlaceholder: '搜索产品、方法或研究方向…',
    searchHint: '搜索产品，或选择你的研究方向。', emptyTitle: '换一个研究问题？',
    emptyText: '没有符合当前条件的工具。试试其他关键词，或查看全部产品。', reset: '查看全部工具',
    heroBottom: '01 — 探索下一个研究起点', creatorRole: '药物发现研究者与 AI 工具开发者', contactLabel: '一起探索',
    capabilitiesLabel: '产品能力', firstWorkflowLabel: '开始使用',
    chooseStage: '选择你的研究起点', stageTools: '这一阶段的工具',
    stageDescriptions: [
      '从文献、医药情报或专利证据开始。让原始来源始终与研究问题相伴。',
      '检查结构，组织研究任务。在选择计算方法前，先理解分子的具体背景。',
      '探索候选生成与分子设计。使用前复核各工具的输入、模型要求和输出。',
      '研究合成路线与起始原料。结合化学判断和来源证据评估路线建议。',
    ],
    closeImage: '关闭图片', loadingImage: '正在加载完整图片…', imageError: '图片加载失败。可打开原始文件重试。',
    openOriginal: '打开原始图片', imageTitle: '仔细看看', sectionNavigation: '页面内容',
    sectionLabels: ['产品能力', '如何开始', '选用前了解'],
  },
  ja: {
    search: '研究ツールを探す', searchPlaceholder: '製品、手法、研究分野を検索…',
    searchHint: '製品を検索するか、研究分野を選んでください。', emptyTitle: '別の研究課題を探しますか？',
    emptyText: '条件に一致するツールがありません。別の語句を試すか、すべての製品をご覧ください。', reset: 'すべてのツールを表示',
    heroBottom: '01 — 次の研究への出発点', creatorRole: '創薬研究者・AI ツール開発者', contactLabel: '一緒に探索',
    capabilitiesLabel: '製品の機能', firstWorkflowLabel: '最初のワークフロー',
    chooseStage: '研究の出発点を選ぶ', stageTools: 'この段階のツール',
    stageDescriptions: [
      '文献、医薬品情報、特許のエビデンスから始めます。研究課題と原典を結び付けてください。',
      '構造を確認し、研究課題を整理します。計算手法を選ぶ前に、分子の背景を確認してください。',
      '候補生成と分子設計を探索します。各ツールの入力、モデル要件、出力を確認してください。',
      '合成経路と出発原料を検討します。化学的判断と出典に基づき、提案された経路を評価してください。',
    ],
    closeImage: '画像を閉じる', loadingImage: '画像全体を読み込み中…', imageError: '画像を読み込めませんでした。元のファイルを開いて再試行できます。',
    openOriginal: '元の画像を開く', imageTitle: '詳しく見る', sectionNavigation: 'このページの内容',
    sectionLabels: ['機能', '始め方', '選択する前に'],
  },
  de: {
    search: 'Forschungswerkzeug finden', searchPlaceholder: 'Tools, Methoden oder Forschungsgebiete suchen…',
    searchHint: 'Durchsuchen Sie die Sammlung oder wählen Sie ein Forschungsgebiet.', emptyTitle: 'Eine andere Forschungsfrage?',
    emptyText: 'Kein Tool passt zu diesen Filtern. Versuchen Sie einen anderen Begriff oder die gesamte Sammlung.', reset: 'Alle Tools anzeigen',
    heroBottom: '01 — DEN NÄCHSTEN SCHRITT ENTDECKEN', creatorRole: 'Wirkstoffforscher und Entwickler von KI-Tools', contactLabel: 'GEMEINSAM ENTDECKEN',
    capabilitiesLabel: 'FUNKTIONEN', firstWorkflowLabel: 'DER ERSTE WORKFLOW',
    chooseStage: 'Wählen Sie Ihren Ausgangspunkt', stageTools: 'Tools für diese Phase',
    stageDescriptions: [
      'Beginnen Sie mit Literatur, Pharma-Informationen oder Patentbelegen. Behalten Sie die Originalquellen zur Forschungsfrage im Blick.',
      'Prüfen Sie Strukturen und ordnen Sie Ihre Forschungsaufgabe. Berücksichtigen Sie den molekularen Kontext vor der Methodenwahl.',
      'Erkunden Sie die Generierung und das Design von Kandidaten. Prüfen Sie Eingaben, Modellanforderungen und Ergebnisse jedes Tools.',
      'Untersuchen Sie Synthesewege und Ausgangsstoffe. Bewerten Sie Vorschläge mit chemischem Fachwissen und Quellenbelegen.',
    ],
    closeImage: 'Bild schließen', loadingImage: 'Vollständiges Bild wird geladen…', imageError: 'Das Bild konnte nicht geladen werden. Öffnen Sie die Originaldatei für einen neuen Versuch.',
    openOriginal: 'Originalbild öffnen', imageTitle: 'Genauer hinsehen', sectionNavigation: 'Auf dieser Seite',
    sectionLabels: ['Funktionen', 'Erste Schritte', 'Vor der Auswahl'],
  },
  fr: {
    search: 'Trouver un outil de recherche', searchPlaceholder: 'Rechercher un outil, une méthode ou un domaine…',
    searchHint: 'Parcourez la collection ou choisissez un domaine de recherche.', emptyTitle: 'Une autre question de recherche ?',
    emptyText: 'Aucun outil ne correspond à ces filtres. Essayez un autre terme ou explorez toute la collection.', reset: 'Afficher tous les outils',
    heroBottom: '01 — EXPLORER LA PROCHAINE ÉTAPE', creatorRole: 'Chercheur en découverte de médicaments et créateur d’outils IA', contactLabel: 'EXPLORONS ENSEMBLE',
    capabilitiesLabel: 'FONCTIONNALITÉS', firstWorkflowLabel: 'VOTRE PREMIER PARCOURS',
    chooseStage: 'Choisissez votre point de départ', stageTools: 'Outils pour cette étape',
    stageDescriptions: [
      'Commencez par la littérature, la veille pharmaceutique ou les données de brevets. Gardez les sources originales liées à votre question.',
      'Examinez les structures et organisez votre travail. Vérifiez le contexte moléculaire avant de choisir une méthode de calcul.',
      'Explorez la génération de candidats et la conception moléculaire. Vérifiez les entrées, les modèles requis et les sorties de chaque outil.',
      'Étudiez les voies de synthèse et les matières premières. Évaluez les suggestions avec votre expertise chimique et les sources disponibles.',
    ],
    closeImage: 'Fermer l’image', loadingImage: 'Chargement de l’image complète…', imageError: 'L’image n’a pas pu être chargée. Ouvrez le fichier original pour réessayer.',
    openOriginal: 'Ouvrir l’image originale', imageTitle: 'Voir de plus près', sectionNavigation: 'Sur cette page',
    sectionLabels: ['Fonctionnalités', 'Premiers pas', 'Avant de choisir'],
  },
  ko: {
    search: '연구 도구 찾기', searchPlaceholder: '제품, 방법 또는 연구 분야 검색…',
    searchHint: '제품을 검색하거나 연구 분야를 선택하세요.', emptyTitle: '다른 연구 질문을 찾으시나요?',
    emptyText: '조건에 맞는 도구가 없습니다. 다른 검색어를 입력하거나 전체 제품을 살펴보세요.', reset: '모든 도구 보기',
    heroBottom: '01 — 다음 연구의 출발점', creatorRole: '신약 개발 연구자 및 AI 도구 개발자', contactLabel: '함께 탐색하기',
    capabilitiesLabel: '제품 기능', firstWorkflowLabel: '첫 워크플로',
    chooseStage: '연구 출발점 선택', stageTools: '이 단계의 도구',
    stageDescriptions: [
      '문헌, 제약 정보 또는 특허 근거에서 시작하세요. 원본 출처를 연구 질문과 함께 검토하세요.',
      '구조를 확인하고 연구 과제를 정리하세요. 계산 방법을 선택하기 전에 분자의 맥락을 검토하세요.',
      '후보 생성과 분자 설계를 탐색하세요. 각 도구의 입력, 모델 요구 사항, 출력을 확인하세요.',
      '합성 경로와 출발 물질을 검토하세요. 화학적 판단과 출처 근거로 경로 제안을 평가하세요.',
    ],
    closeImage: '이미지 닫기', loadingImage: '전체 이미지를 불러오는 중…', imageError: '이미지를 불러오지 못했습니다. 원본 파일을 열어 다시 시도할 수 있습니다.',
    openOriginal: '원본 이미지 열기', imageTitle: '자세히 보기', sectionNavigation: '이 페이지의 내용',
    sectionLabels: ['기능', '시작하기', '선택 전 확인'],
  },
};
