// Structure-control translations; preserve source-owned chemical identifiers.
export const structureLabels = {
  "en": {
    "colorLegend": "Color legend",
    "helix": "Helix",
    "sheet": "Sheet",
    "loop": "Loop",
    "chain": "Chain",
    "carbon": "Carbon",
    "nitrogen": "Nitrogen",
    "oxygen": "Oxygen",
    "atoms": "Deposited atoms",
    "chains": "Protein chains",
    "resolution": "Resolution",
    "noScript": "Open the published records to explore these structures without JavaScript.",
    "motionReduced": "Automatic rotation is paused by your motion preference.",
    "sulfur": "Sulfur",
    "iron": "Iron"
  },
  "zh": {
    "colorLegend": "颜色图例",
    "helix": "螺旋",
    "sheet": "折叠",
    "loop": "环区",
    "chain": "链",
    "carbon": "碳",
    "nitrogen": "氮",
    "oxygen": "氧",
    "atoms": "原始坐标原子数",
    "chains": "蛋白链",
    "resolution": "分辨率",
    "noScript": "未启用 JavaScript 时，可打开公开记录查看这些结构。",
    "motionReduced": "已根据你的动态效果偏好暂停自动旋转。",
    "sulfur": "硫",
    "iron": "铁"
  },
  "ja": {
    "colorLegend": "配色の凡例",
    "helix": "ヘリックス",
    "sheet": "シート",
    "loop": "ループ",
    "chain": "鎖",
    "carbon": "炭素",
    "nitrogen": "窒素",
    "oxygen": "酸素",
    "atoms": "登録された原子数",
    "chains": "タンパク質鎖",
    "resolution": "分解能",
    "noScript": "JavaScript を使わずに構造を見るには、公開された記録を開いてください。",
    "motionReduced": "動きの設定に合わせて自動回転を停止しています。",
    "sulfur": "硫黄",
    "iron": "鉄"
  },
  "de": {
    "colorLegend": "Farblegende",
    "helix": "Helix",
    "sheet": "Faltblatt",
    "loop": "Schleife",
    "chain": "Kette",
    "carbon": "Kohlenstoff",
    "nitrogen": "Stickstoff",
    "oxygen": "Sauerstoff",
    "atoms": "Hinterlegte Atome",
    "chains": "Proteinketten",
    "resolution": "Auflösung",
    "noScript": "Öffnen Sie die veröffentlichten Einträge, um diese Strukturen ohne JavaScript zu erkunden.",
    "motionReduced": "Die automatische Rotation ist entsprechend Ihrer Bewegungseinstellung pausiert.",
    "sulfur": "Schwefel",
    "iron": "Eisen"
  },
  "fr": {
    "colorLegend": "Légende des couleurs",
    "helix": "Hélice",
    "sheet": "Feuillet",
    "loop": "Boucle",
    "chain": "Chaîne",
    "carbon": "Carbone",
    "nitrogen": "Azote",
    "oxygen": "Oxygène",
    "atoms": "Atomes déposés",
    "chains": "Chaînes protéiques",
    "resolution": "Résolution",
    "noScript": "Ouvrez les fiches publiées pour explorer ces structures sans JavaScript.",
    "motionReduced": "La rotation automatique est suspendue selon votre préférence de mouvement.",
    "sulfur": "Soufre",
    "iron": "Fer"
  },
  "ko": {
    "colorLegend": "색상 범례",
    "helix": "나선",
    "sheet": "시트",
    "loop": "루프",
    "chain": "사슬",
    "carbon": "탄소",
    "nitrogen": "질소",
    "oxygen": "산소",
    "atoms": "등록된 원자 수",
    "chains": "단백질 사슬",
    "resolution": "해상도",
    "noScript": "JavaScript 없이 구조를 살펴보려면 공개 기록을 여세요.",
    "motionReduced": "동작 설정에 따라 자동 회전이 일시 중지되었습니다.",
    "sulfur": "황",
    "iron": "철"
  }
};
